'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import PageHero from '@/app/components/PageHero';

/**
 * ScanClient — camera-based QR scanner for assets.
 *
 * Users can:
 *   1. Click "Start Scanner" to open the device camera
 *   2. Point at a printed asset label (QR generated by /api/assets/:id/qr)
 *   3. On successful scan, we extract the asset tag and redirect to
 *      the asset detail page
 *   4. As a fallback, they can type an asset tag manually and submit
 *
 * The scanner library (html5-qrcode) is loaded lazily so the page can
 * render instantly even if the user never starts the camera.
 */
export default function ScanClient({ initialTag }: { initialTag: string }) {
  const router = useRouter();
  const [scanning, setScanning] = useState(false);
  const [manualTag, setManualTag] = useState(initialTag);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState<string | null>(null);
  const scannerRef = useRef<any>(null);

  // If arriving via a QR URL like /assets/scan?tag=ABC, auto-resolve.
  useEffect(() => {
    if (initialTag) {
      resolveAndGo(initialTag).catch(() => {
        setError(`No asset found for tag "${initialTag}".`);
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialTag]);

  async function resolveAndGo(rawText: string) {
    setError(null);
    setStatus('Looking up asset…');
    // If the scanned payload is a full URL (as generated by the QR route),
    // extract the "tag" query parameter.
    let tag = rawText.trim();
    try {
      if (/^https?:\/\//i.test(tag)) {
        const u = new URL(tag);
        tag = u.searchParams.get('tag') || tag;
      }
    } catch {
      // not a URL — fall through
    }
    tag = tag.trim();
    if (!tag) throw new Error('Empty tag');

    const res = await fetch(`/api/assets/by-tag/${encodeURIComponent(tag)}`);
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      throw new Error(body.error || 'Not found');
    }
    const data = await res.json();
    setStatus('Found! Redirecting…');
    router.push(`/assets/${data.id}`);
  }

  async function startScanner() {
    setError(null);
    setStatus(null);
    setScanning(true);
    try {
      // Lazy import html5-qrcode only when the user actually clicks start.
      const { Html5Qrcode } = await import('html5-qrcode');
      const scanner = new Html5Qrcode('qr-reader');
      scannerRef.current = scanner;

      await scanner.start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 260, height: 260 } },
        async (decodedText: string) => {
          // Success — stop the camera then resolve the tag.
          try {
            await scanner.stop();
          } catch {
            /* ignore */
          }
          setScanning(false);
          try {
            await resolveAndGo(decodedText);
          } catch (err: any) {
            setError(err?.message || 'Could not resolve that asset');
          }
        },
        // onScanFailure is noisy (fires every frame that misses) — ignore.
        undefined
      );
    } catch (err: any) {
      setScanning(false);
      const name = err?.name || '';
      let msg = err?.message || 'Could not start the camera.';
      if (
        name === 'NotAllowedError' ||
        name === 'PermissionDeniedError' ||
        msg.includes('Permission')
      ) {
        msg = 'Camera permission was denied. Please allow camera access in your browser settings.';
      } else if (name === 'NotFoundError') {
        msg = 'No camera was found on this device.';
      } else if (name === 'NotReadableError') {
        msg = 'The camera is already in use by another app.';
      }
      // Check HTTPS requirement
      if (
        typeof window !== 'undefined' &&
        window.location.protocol !== 'https:' &&
        window.location.hostname !== 'localhost' &&
        window.location.hostname !== '127.0.0.1'
      ) {
        msg += ' Note: Camera access requires HTTPS. Your site is running on HTTP which blocks camera access.';
      }
      setError(msg);
    }
  }

  async function stopScanner() {
    try {
      if (scannerRef.current) {
        await scannerRef.current.stop();
      }
    } catch {
      /* ignore */
    }
    setScanning(false);
  }

  // Clean up on unmount — guard against double-stop (success callback
  // already stops the scanner before navigation, so the unmount cleanup
  // would otherwise log "Cannot stop, scanner is not running or paused").
  useEffect(() => {
    return () => {
      const s = scannerRef.current;
      if (s && typeof s.getState === 'function') {
        try {
          const state = s.getState();
          // Only stop if still scanning (state 2 = SCANNING, 3 = PAUSED)
          if (state === 2 || state === 3) {
            s.stop().catch(() => {});
          }
        } catch {
          // getState itself can throw if scanner was never started
        }
      } else if (s) {
        s.stop().catch(() => {});
      }
    };
  }, []);

  async function handleManualSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!manualTag.trim()) return;
    try {
      await resolveAndGo(manualTag);
    } catch (err: any) {
      setError(err?.message || 'Not found');
      setStatus(null);
    }
  }

  return (
    <div className="max-w-2xl mx-auto">
      <PageHero
        eyebrow="Assets / Scanner"
        title="Scan Asset"
        description="Point your camera at a printed asset label's QR code. When the code is decoded you'll be sent straight to that asset's detail page."
        actions={
          <Link href="/assets" className="btn btn-secondary">
            All Assets →
          </Link>
        }
      />

      {/* Camera scanner area */}
      <div className="card">
        <div className="card-body">
          <div
            id="qr-reader"
            className="w-full max-w-md mx-auto bg-gray-900 rounded-lg overflow-hidden"
            style={{ minHeight: scanning ? 280 : 80 }}
          />

          <div className="flex justify-center gap-3 mt-4">
            {!scanning ? (
              <button onClick={startScanner} className="btn btn-primary">
                📷 Start Scanner
              </button>
            ) : (
              <button onClick={stopScanner} className="btn btn-secondary">
                ✕ Stop Scanner
              </button>
            )}
          </div>

          {status && (
            <p className="text-center text-sm text-brand-primary mt-3">
              {status}
            </p>
          )}
          {error && (
            <p className="text-center text-sm text-red-600 mt-3">{error}</p>
          )}
        </div>
      </div>

      {/* Manual entry fallback */}
      <div className="card mt-6">
        <div className="card-header">
          <h2 className="section-heading">Enter Tag Manually</h2>
        </div>
        <div className="card-body">
          <form onSubmit={handleManualSubmit} className="flex gap-3">
            <input
              type="text"
              value={manualTag}
              onChange={(e) => setManualTag(e.target.value)}
              placeholder="e.g. LAPTOP-0001"
              className="form-input flex-1 font-mono"
            />
            <button type="submit" className="btn btn-primary">
              Look Up
            </button>
          </form>
          <p className="text-xs text-gray-500 mt-2">
            Useful if the label is damaged or the camera is unavailable.
          </p>
        </div>
      </div>
    </div>
  );
}
