// Import script: Reads extracted JSON from Access DB and seeds into 99 ERP
// Run: npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/import-access-db.ts

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

// This data is extracted from the Access DB via Python
// We'll read it from a JSON file generated by the extraction step
import * as fs from 'fs';

async function main() {
  const dataPath = __dirname + '/access-export.json';
  if (!fs.existsSync(dataPath)) {
    console.error('❌ access-export.json not found. Run the Python extraction first.');
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
  const assets: any[] = data.assets;
  const contacts: any[] = data.contacts;

  console.log(`📦 Found ${assets.length} assets and ${contacts.length} contacts to import`);

  // 1. Ensure Laptop category exists
  let laptopCategory = await prisma.assetCategory.findFirst({ where: { code: 'LAPTOP' } });
  if (!laptopCategory) {
    laptopCategory = await prisma.assetCategory.create({
      data: { name: 'Laptop', code: 'LAPTOP', description: 'Laptop computers' },
    });
  }
  console.log(`✅ Laptop category ID: ${laptopCategory.id}`);

  // 2. Get default company and location
  const defaultCompany = await prisma.company.findFirst({ orderBy: { id: 'asc' } });
  const defaultLocation = await prisma.location.findFirst({ orderBy: { id: 'asc' } });
  if (!defaultCompany || !defaultLocation) {
    console.error('❌ No company or location found. Please seed base data first.');
    process.exit(1);
  }

  // 3. Build a contact lookup from the imported contacts
  // Create a map: Access contact ID -> employee record
  const contactMap: Record<number, any> = {};
  for (const c of contacts) {
    contactMap[c.id] = c;
  }

  // 4. Get existing employees by name for matching
  const existingEmployees = await prisma.employee.findMany({
    select: { id: true, firstName: true, lastName: true },
  });
  const empByName: Record<string, number> = {};
  for (const emp of existingEmployees) {
    const key = `${emp.firstName} ${emp.lastName}`.toLowerCase().trim();
    empByName[key] = emp.id;
  }

  // 5. Import assets
  let created = 0;
  let skipped = 0;
  let assigned = 0;

  for (const asset of assets) {
    const assetTag = asset.item; // e.g. "Laptop-01"

    // Check if already exists
    const existing = await prisma.asset.findFirst({ where: { assetTag } });
    if (existing) {
      skipped++;
      continue;
    }

    // Determine condition
    let condition: 'WORKING' | 'DAMAGED' | 'LOST' | 'RETIRED' | 'NEW' = 'WORKING';
    const comments = (asset.comments || '').toLowerCase();
    const ownerName = asset.ownerName || '';

    if (comments.includes('damage') || comments.includes('lost')) {
      condition = 'DAMAGED';
    }
    if (ownerName === 'Retired Asset') {
      condition = comments.includes('lost') ? 'LOST' : 'RETIRED';
    }

    const isRetired = ownerName === 'Retired Asset';
    const isAvailable = ownerName === 'Available';
    const isAssigned = !isRetired && !isAvailable && ownerName !== '';

    // Extract manufacturer from model string
    const modelStr = asset.model || '';
    let manufacturer = asset.manufacturer || 'Unknown';
    let serialNumber = modelStr;

    // The model field contains the serial like "Dell-65QGRC2" or "HP-5CG5062RNH"
    // Use as serial number directly
    if (!serialNumber) serialNumber = `${assetTag}-SERIAL`;

    const newAsset = await prisma.asset.create({
      data: {
        assetTag,
        serialNumber,
        categoryId: laptopCategory.id,
        manufacturer,
        model: manufacturer === 'Dell' ? 'Latitude' : manufacturer === 'HP' ? 'ProBook' : 'Unknown',
        purchaseDate: asset.acquiredDate ? new Date(asset.acquiredDate) : new Date('2023-01-01'),
        purchasePrice: asset.purchasePrice || 0,
        currency: 'PKR',
        condition,
        companyId: defaultCompany.id,
        locationId: defaultLocation.id,
        isAssigned,
        isRetired,
        retireReason: isRetired ? (comments || 'Retired from Access DB') : null,
        retiredDate: isRetired ? new Date('2024-01-01') : null,
        batchId: asset.condition || null, // "Batch 1", "Batch 2" etc stored here
        notes: asset.comments || null,
        specs: {
          description: asset.description || null,
          importedFrom: 'Access DB',
          originalId: asset.id,
          batch: asset.condition || null,
        },
      },
    });

    created++;

    // If assigned to a real person, try to create an assignment
    if (isAssigned && ownerName) {
      const ownerKey = ownerName.toLowerCase().trim();
      const empId = empByName[ownerKey];

      if (empId) {
        await prisma.assetAssignment.create({
          data: {
            assetId: newAsset.id,
            employeeId: empId,
            assignedDate: new Date(),
            conditionAtAssignment: condition === 'WORKING' ? 'WORKING' : condition,
            notes: `Imported from Access DB. Batch: ${asset.condition || 'N/A'}`,
          },
        });
        assigned++;
      }
      // If employee not found in DB, store the owner name in notes
      else {
        await prisma.asset.update({
          where: { id: newAsset.id },
          data: {
            notes: `${asset.comments || ''} [Owner from Access DB: ${ownerName}]`.trim(),
          },
        });
      }
    }
  }

  // 6. Create audit log
  await prisma.auditLog.create({
    data: {
      tableName: 'assets',
      recordId: 0,
      action: 'CREATE',
      module: 'ASSET',
      newValues: {
        action: 'BULK_IMPORT',
        source: 'Access DB',
        totalAssets: assets.length,
        created,
        skipped,
        assigned,
      },
    },
  });

  console.log(`\n✅ Import complete!`);
  console.log(`   Created: ${created}`);
  console.log(`   Skipped (already exist): ${skipped}`);
  console.log(`   Assigned to employees: ${assigned}`);
}

main()
  .catch((e) => {
    console.error('Import error:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
